[colors.bright]
black = "#212121"
blue = "#20bbfc"
cyan = "#4fb8cc"
green = "#5fd7af"
magenta = "#6855de"
red = "#fb007a"
white = "#f1f1f1"
yellow = "#f3e430"

[colors.normal]
black = "#212121"
blue = "#008ec4"
cyan = "#20a5ba"
green = "#10a778"
magenta = "#523c79"
red = "#c30771"
white = "#e0e0e0"
yellow = "#a89c14"

[colors.primary]
background = "#f1f1f1"
dim_foreground = "#808080"
foreground = "#424242"

[font]
size = 14.0

[font.italic]
style = "Oblique"
