[defaults]
vars.curl = "curl -Ssf -L"

binary = "${name}-${version}"

[refactor]
vars.version = "0.13.0.0"

install = """
  stack install --local-bin-path $(pwd) apply-refact-${version}
  cp -v ./${name} "$1"
"""

[restyle]
vars.version = "0.6.0.2"

install = """
  mkdir -p ./bin
  curl --proto '=https' --tlsv1.2 -sSf \
    https://raw.githubusercontent.com/restyled-io/restyler/main/install |
      sh -s -- -p $(pwd) -t v${version}
  cp -v ./bin/${name} "$1"
"""

[fast-tags]
vars.version = "2.0.2"

install = """
  stack install --local-bin-path $(pwd) ${name}-${version}
  cp -v ./${name} "$1"
"""

[fourmolu]
vars.version = "0.18.0.0"
vars.artifact = "${name}-${version}-linux-x86_64"

install = """
  ${curl} -O https://github.com/${name}/${name}/releases/download/v${version}/${artifact}
  install ${artifact} "$1"
"""

[hadolint]
vars.version = "2.12.0"

install = """
  ${curl} -o ${name} https://github.com/${name}/${name}/releases/download/v${version}/${name}-Linux-x86_64
  chmod +x ./${name}
  cp -v ./${name} "$1"
"""

[headroom]
vars.version = "0.4.3.0"

install = """
  stack install --local-bin-path $(pwd) ${name}-${version}
  cp -v ./${name} "$1"
"""

[hlint]
vars.version = "3.8"

install = """
  ${curl} https://github.com/ndmitchell/${name}/releases/download/v${version}/${name}-${version}-x86_64-linux.tar.gz | tar xzf -
  cp -v ${name}-${version}/${name} "$1"
"""

[pandoc]
vars.version = "3.5"

install = """
  ${curl} https://github.com/jgm/${name}/releases/download/${version}/${name}-${version}-linux-amd64.tar.gz | tar xzf -
  cp -v ${name}-${version}/bin/${name} "$1"
"""

[platform]
vars.version = "3.2.17.0"
vars.archive = "${name}-x86_64-linux.tar.gz"

install = """
  gh --repo freckle/${name} release download --pattern ${archive} v${version}
  tar xzf ${archive}
  cp -v ${name}/${name} "$1"
"""

[shellcheck]
vars.version = "stable"

install = """
  ${curl} https://github.com/koalaman/${name}/releases/download/${version}/${name}-${version}.linux.x86_64.tar.xz | tar xJf -
  cp -v ${name}-${version}/${name} "$1"
"""

[stackctl]
vars.version = "1.7.2.0"

install = """
  ${curl} https://github.com/freckle/${name}/releases/download/v${version}/${name}-x86_64-linux.tar.gz | tar xzf -
  cp -v ${name}/${name} "$1"
"""

[stack-all]
vars.version = "0.6.4"

install = """
  stack install --local-bin-path $(pwd) ${name}-${version}
  cp -v ./${name} "$1"
"""

[stack-lint-extra-deps]
vars.version = "1.3.0.0"

install = """
  ${curl} https://github.com/freckle/${name}/releases/download/v${version}/${name}-x86_64-linux.tar.gz | tar xzf -
  cp -v ${name}/${name} "$1"
"""

[yq]
vars.version = "4.45.1"

install = """
  ${curl} -O https://github.com/mikefarah/${name}/releases/download/v${version}/${name}_linux_amd64
  chmod +x ./${name}_linux_amd64
  cp -v ./${name}_linux_amd64 "$1"
"""
