filetype off

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Plugin 'gmarik/vundle'
Plugin 'bogado/file-line'
Plugin 'kien/ctrlp.vim'
Plugin 'nicholaides/words-to-avoid.vim'
Plugin 'pbrisbin/vim-colors-off'
Plugin 'pbrisbin/vim-mkdir'
Plugin 'pbrisbin/vim-rename-file'
Plugin 'pbrisbin/vim-restore-cursor'
Plugin 'pbrisbin/vim-runfile'
Plugin 'pbrisbin/vim-syntax-shakespeare'
Plugin 'scrooloose/syntastic'
Plugin 'slim-template/vim-slim'
Plugin 'thoughtbot/vim-rspec'
Plugin 'tpope/vim-bundler'
Plugin 'tpope/vim-commentary'
Plugin 'tpope/vim-endwise'
Plugin 'tpope/vim-eunuch'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-rails'
Plugin 'tpope/vim-rake'
Plugin 'tpope/vim-repeat'
Plugin 'tpope/vim-surround'
Plugin 'vim-ruby/vim-ruby'

syntax on
filetype plugin indent on

set autoindent
set autoread
set autowrite
set background=dark
set colorcolumn=+1
set cursorline
set diffopt+=vertical
set directory=/tmp
set expandtab
set foldmethod=marker
set formatoptions+=j
set grepprg=git\ grep\ -n\ $*
set history=500
set hlsearch
set incsearch
set laststatus=2
set list listchars=tab:»·,trail:·
set nobackup
set nojoinspaces
set notitle
set nowrap
set number
set ruler
set scrolloff=999
set shiftwidth=2
set showcmd
set showmatch
set sidescroll=1
set sidescrolloff=5
set smartindent
set smarttab
set textwidth=80
set visualbell t_vb=
set wildmode=list:longest
set winwidth=84

silent! colorscheme off

let mapleader = ' '
let maplocalleader = ' '

let g:ctrlp_use_caching  = 0
let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files | grep -Fv node_modules']
let g:rspec_command      = '!bundle exec rspec -c {spec}'
let g:runfile_by_name    = {
  \   '.*\.t$': '!cram %',
  \   '.*\.lhs$': '!runhaskell %',
  \   '.*Gemfile$': '!bundle',
  \   '.*\.md$': '!opandoc %',
  \   '.*Spec\.hs$': '!echo :main | cabal exec -- ghci -v0 %',
  \   '.*\.hs$': '!cabal exec -- ghci %',
  \   '.*\.tex$': '!pdflatex %'
  \ }
let g:syntastic_mode_map = {
  \ "mode": "passive",
  \ "active_filetypes": ["javascript"]
  \ }

map <Leader>a :call RunAllSpecs()<CR>
map <Leader>s :call RunNearestSpec()<CR>
map <Leader>t :call RunCurrentSpecFile()<CR>
map <Leader>n :RenameFile<CR>
map <Leader>r :Run<CR>

nnoremap <C-l> :<C-u>nohlsearch<CR><C-l>

augroup vimrc
  autocmd!
  autocmd BufEnter *.md,*.mkd setlocal filetype=markdown
  autocmd BufWritePost *.tex execute ':Run' | execute ':redraw!'
  autocmd FileType cram setlocal formatoptions+=twn
  autocmd FileType haskell setlocal shiftwidth=4
  autocmd FileType html,eruby setlocal noshowmatch " causes lag in these filetypes
  autocmd FileType mail setlocal spell nohlsearch
  autocmd FileType gitcommit,markdown,lhaskell setlocal nosmartindent | setlocal spell
augroup END
