filetype off

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Plugin 'gmarik/vundle'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'pbrisbin/vim-mkdir'
Plugin 'pbrisbin/vim-rename-file'
Plugin 'pbrisbin/vim-restore-cursor'
Plugin 'pbrisbin/vim-runfile'
Plugin 'pbrisbin/vim-syntax-shakespeare'
Plugin 'slim-template/vim-slim'
Plugin 'thoughtbot/vim-rspec'
Plugin 'tpope/vim-bundler'
Plugin 'tpope/vim-commentary'
Plugin 'tpope/vim-endwise'
Plugin 'tpope/vim-eunuch'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-rails'
Plugin 'tpope/vim-rake'
Plugin 'tpope/vim-repeat'
Plugin 'tpope/vim-sensible'
Plugin 'tpope/vim-surround'
Plugin 'vim-ruby/vim-ruby'

set autoread
set autowrite
set colorcolumn=+1
set diffopt+=vertical
set expandtab
set grepprg=git\ grep\ -n\ $*
set list
set nojoinspaces
set nowrap
set number
set shiftwidth=2
set smarttab
set textwidth=80

let mapleader = ' '
let maplocalleader = ' '

let g:ctrlp_use_caching  = 0
let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files']
let g:rspec_command      = '!bundle exec rspec -c {spec}'
let g:runfile_debug      = 1
let g:runfile_by_name    = {
  \   'Gemfile$': '!bundle',
  \   'Spec\.hs$': '!stack exec ghc -- -e main %',
  \   '.*\.cabal$': '!stack install --dependencies-only --enable-tests',
  \   '.*_spec\.rb$': '!bundle exec ruby -Ilib -Ispec %',
  \ }
let g:runfile_by_type    = {
  \ 'haskell': '!stack exec -- ghci -Wall %',
  \ 'lhaskell': '!stack exec -- ghci -Wall %'
  \ }

map <Leader>a :call RunAllSpecs()<CR>
map <Leader>s :call RunNearestSpec()<CR>
map <Leader>t :call RunCurrentSpecFile()<CR>
map <Leader>n :RenameFile<CR>
map <Leader>r :Run<CR>

augroup vimrc
  autocmd!
  autocmd FileType haskell setlocal shiftwidth=4
  autocmd FileType gitcommit,hamlet,lhaskell,mail,markdown setlocal spell
augroup END
