filetype off

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Plugin 'gmarik/vundle'
Plugin 'kien/ctrlp.vim'
Plugin 'pbrisbin/alt-ctags'
Plugin 'pbrisbin/vim-mkdir'
Plugin 'pbrisbin/vim-rename-file'
Plugin 'pbrisbin/vim-restore-cursor'
Plugin 'pbrisbin/vim-runfile'
Plugin 'thoughtbot/vim-rspec'
Plugin 'tpope/vim-bundler'
Plugin 'tpope/vim-commentary'
Plugin 'tpope/vim-endwise'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-rails'
Plugin 'tpope/vim-rake'
Plugin 'tpope/vim-repeat'
Plugin 'tpope/vim-surround'
Plugin 'vim-ruby/vim-ruby'

filetype plugin indent on

set autoindent
set autoread
set autowrite
set background=dark
set directory=/tmp
set expandtab
set foldmethod=marker
set formatoptions-=t
set formatoptions+=j
set history=500
set hlsearch
set incsearch
set laststatus=2
set list listchars=tab:»·,trail:·
set nobackup
set nojoinspaces
set nowrap
set number
set ruler
set scrolloff=999
set shiftwidth=2
set showcmd
set showmatch
set sidescroll=1
set sidescrolloff=5
set smartindent
set smarttab
set textwidth=80
set visualbell t_vb=
set wildmode=list:longest
set winwidth=84

let mapleader = ' '
let maplocalleader = ' '

let g:ctags_command      = "ctags -f '%f' -R --exclude='*.js'"
let g:ctags_excludes     = ['~', '~/.dotfiles/', '~/Code/pbrisbin.com']
let g:ctrlp_use_caching  = 0
let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files']
let g:rspec_command      = '!bundle exec rspec -c {spec}'
let g:runfile_by_name    = {
  \   '.*\.t': '!cram %',
  \   '.*\.lhs': '!runhaskell %',
  \   '.*Gemfile': '!bundle',
  \   '.*\.md': '!opandoc %'
  \ }

map <Leader>a :call RunAllSpecs()<CR>
map <Leader>s :call RunNearestSpec()<CR>
map <Leader>t :call RunCurrentSpecFile()<CR>
map <Leader>n :RenameFile<CR>
map <Leader>r :Run<CR>

nnoremap <C-l> :<C-u>nohlsearch<CR><C-l>

cmap w!! execute ":silent w !sudo tee % >/dev/null" \| edit! \| redraw!<CR>

command! -range=% Paste :<line1>,<line2>write !curl -sF "f:1=<-" http://ix.io
command! -nargs=* RSpec execute '!bundle exec rspec '.join([<f-args>], ' ')

function! SetProseOptions()
  setlocal formatoptions+=twn
  setlocal nosmartindent
  setlocal spell
  setlocal textwidth=72
endfunction

augroup vimrc
  autocmd!
  autocmd BufEnter *.md,*.mkd setlocal filetype=markdown
  autocmd FileType cram setlocal formatoptions+=twn
  autocmd FileType haskell setlocal shiftwidth=4 | let b:ctags_command = 'hs-ctags %f'
  autocmd FileType html,eruby setlocal noshowmatch " causes lag in these filetypes
  autocmd FileType mail setlocal spell nohlsearch
  autocmd FileType gitcommit,markdown,lhaskell call SetProseOptions()
augroup END
