#!/bin/bash
#
# Aurget v4 config file. Place this file at:
#
#  $XDG_CONFIG_HOME/aurgetrc
#
# Which is typically:
#
#  ~/.config/aurgetrc
#
###

# The directory within which to build.
build_directory="$HOME/Sources"

# Should aurget remove the extracted source directory after processing?
discard_sources=true

# When to edit PKGBUILDs. One of prompt, always, or never.
edit_pkgbuilds='never'

# Space separated list of packages to ignore
ignore_packages=''

# If you choose to discard sources, you can separately choose to NOT
# discard sources for development packages.
keep_devels=true

# The makepkg executable
makepkg='makepkg'

# The default options to pass to makepkg. Other options may be added for
# you depending on the package (--asdeps) or sync_mode (--install).
makepkg_options='--syncdeps'

# When true, aurget will source PKGBUILDs and attempt to resolve
# dependencies.
resolve_dependencies=true

# The default way to process packages for -S and -Su. Can be one of
# download, build, or install.
sync_mode='install'

# Where aurget will place temporary working files as needed. This
# directory is created and cleared when aurget starts.
temp_directory='/tmp/aurget'

# Colors
colorR="\e[1;31m"
colorG="\e[1;32m"
colorY="\e[1;33m"
colorB="\e[1;34m"
colorM="\e[1;35m"
colorC="\e[1;36m"
colorW="\e[1;37m"
nocolor="\e[0m"
