#!/bin/sh
chmod 0600 ~/.netrc.gpg

if [ ! -d ~/.config/nvim/pack/minpac/opt/minpac ]; then
  git clone https://github.com/k-takata/minpac.git \
    ~/.config/nvim/pack/minpac/opt/minpac
fi

if [ ! -f ~/.local/share/nvim/site/syntax/cram.vim ]; then
  curl -fLo ~/.local/share/nvim/site/syntax/cram.vim --create-dirs \
    "https://raw.githubusercontent.com/brodie/cram/master/contrib/cram.vim"
fi

if [ "${STACK_INSTALL:-1}" -eq 1 ] && command -v stack >/dev/null; then
  (
    # Ensure we're always in ~/ when we run this
    cd && stack install \
      ShellCheck \
      xmonad \
      xmonad-contrib
  )
fi
