#!/bin/sh
if [ -f ~/.netrc.gpg ]; then
  chmod 0600 ~/.netrc.gpg
fi

if [ -d ~/.config/gnupg ]; then
  chmod 0700 ~/.config/gnupg
fi

if [ ! -d ~/.config/nvim/pack/minpac/opt/minpac ]; then
  git clone https://github.com/k-takata/minpac.git \
    ~/.config/nvim/pack/minpac/opt/minpac
fi

if [ ! -f ~/.local/share/nvim/site/syntax/cram.vim ]; then
  curl -fLo ~/.local/share/nvim/site/syntax/cram.vim --create-dirs \
    "https://raw.githubusercontent.com/brodie/cram/master/contrib/cram.vim"
fi

if [ ! -d ~/.password-store ]; then
  git clone git@gitlab.com:pbrisbin/password-store.git ~/.password-store
fi
