#!/bin/sh
xrandr | grep -Fq 'DP1 connected' && \
  xrandr --output DP1 --mode 2560x1600 --right-of LVDS1

feh --bg-tile ~/.background.png

xset s off
xset fp+ /usr/share/fonts/local
xsetroot -cursor_name left_ptr
setxkbmap -option terminate:ctrl_alt_bksp

xcompmgr -fF &
android-receiver &

urxvtd -q -f -o

xmonad
