set -o vi

export XDG_CACHE_HOME="$HOME"/.cache
export XDG_CONFIG_HOME="$HOME"/.config
export XDG_DATA_HOME="$HOME"/.local/share

export GNUPGHOME="$XDG_CONFIG_HOME"/gnupg
export LESSHISTFILE="$XDG_CACHE_HOME"/lesshist
export NOTMUCH_CONFIG="$XDG_CONFIG_HOME"/notmuchrc
export RCRC="$XDG_CONFIG_HOME"/rcrc
export SCREENRC="$XDG_CONFIG_HOME"/screenrc
export XAUTHORITY="$XDG_RUNTIME_DIR"/X11-authority

export PATH="$HOME/.local/bin:$PATH"

alias g='git'
alias p='sudo pacman'

if [ -r /usr/share/bash-completion/bash_completion ]; then
  source /usr/share/bash-completion/bash_completion
fi
