#!/bin/sh

msu # Monitor Setup Utility

dunst &
xrdb "$XDG_CONFIG_HOME"/Xresources
xset s off
xsetroot -cursor_name left_ptr
urxvtd -q -f -o
xautolock -time 5 -locker slock -secure &

stack exec xmonad
